# Project info
site_name: CAPE Docs
site_description: The official website and documentation site for CAPE
site_author: CAPE Docs
site_url: https://docs.cape.sh

copyright: Copyright &copy; 2020-2022 CAPE

# Configuration
theme:
  name: material
  logo: img/capeicon.png
  favicon: img/capeicon.png
  palette:
    scheme: slate
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top

extra_css:
    - stylesheets/extra.css

extra:
  generator: false

plugins:
  - git-revision-date

  # Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true


# Navigation
nav:
  - Introduction:
    - What is CAPE: introduction/what_is_CAPE.md
    - Features: introduction/features.md
    - Architecture: introduction/architecture.md
    - Use Cases: introduction/use_cases.md
  - Release Notes:
    - Ver 0.1: release-notes/0.1.md
  - Getting Started:
    - Download: getting-started/download.md
    - Install: getting-started/install.md
    - Authentication: getting-started/authentication.md 
    - Using CAPE CLI/Command set: getting-started/using_CAPE_CLI_command_set.md
    - Connect to cluster: getting-started/connect_to_cluster.md
    - Connect to Repo: getting-started/connect_to_repo.md
    - Deploy sample app: getting-started/deploy_sample_app.md
  - Deployment:
    - Deployment Dashboard: deployment/deployment_dashboard.md
    - Define Apps Definition and Rules: deployment/define_apps_definition_and_rules.md
    - Schedule Deployment: deployment/schedule_deployments.md 
    - Rollback Deployment: deployment/rollback_deployment.md
    - Deploy to K8S/K3 Clusters: deployment/deploy_to_K8s_K3s.md
    - Deploy from Image Registries: deployment/deploy_from_image_registries.md
    - Deploy from Package Managment Tools: deployment/deploy_from_package_managment_tools.md
  - Account Settings: account_settings.md
  - FAQs: faqs.md
  - Roadmap: roadmap.md